name: Servant Info
description: Some servants' info seems incorrect
labels: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 在提问之前...
      options:
      - label: 我的问题是有从者的技能没有合理地施放
        required: true
      - label: 我已经搜索了现有的 issues 和 discussions
        required: true
      - label: 我正在使用最新版的 FGO-py
        required: true
  - type: textarea
    id: servantid
    attributes:
      label: 从者编号
      description: |
        提供你认为技能施放放有问题的从者的编号
        例如<伊莉雅丝菲尔·冯·爱因兹贝伦>的编号为136
        而<伊莉雅丝菲尔·冯·爱因兹贝伦(Archer)>的编号为286
        在游戏内 个人空间-卡牌图鉴-灵基一览 中选择按ID排序可以查看
        或者你也可以提供足以确定是哪个从者的信息
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: 描述
      description: |
        通常你不需要填写本字段,开发者会完成剩下的所有工作
        但是如果你对相关技能的施放行为有自己的想法,就简单写一些吧
    validations:
      required: false
